### ISSUE TITLE
Lecture 1 question

### ISSUE THREAD

**Issue by DenisBelinov** [fmi/java-course#57]
Сигурни ли сте, че https://github.com/fmi/java-course/blame/master/01-intro-to-java/lecture/PITCHME.md#L651 работи?

Според https://docs.oracle.com/en/java/javase/13/docs/api/java.base/java/util/Arrays.html Arrays.sort(char[] a) връща void. В лекцията се извиква .toString() директно на return value-то, но няма такова. 

Когато го изпробвах, още IDEто ми се кара с cannot resolve method.

ПС: Не знам дали тук трябваше да вдигам issue-та, ако не е правилното място се извинявам :/

**Comment by ialidzhikov** [comment]
Nice catch!

**Comment by ialidzhikov** [comment]
@DenisBelinov , може ли да пуснеш PR към `mjt-2018-2019` branch-a?
