### ISSUE TITLE
testIfPaymentFailsIfNullPaymentIsPassed passes when it shouldn't

### ISSUE THREAD

**Issue by DenisBelinov** [fmi/java-course#58]
https://github.com/fmi/java-course/blob/f61ebad69110e7cf01ffb4751dce7a82bbe88e55/02-oop-in-java-i/lab/SampleVirtualWalletTest.java#L80

Този тест ми минава, без да имам check за null PaymentInfo. Причината е, че проверявам дали картата е регистрирана първо и понеже не е -> return false.

Fix:
`assertTrue(wallet.registerCard(standardCard));
 assertFalse(wallet.executePayment(standardCard, null));`

**Comment by KristianZH** [comment]
@yordanovagabriela @100yo

**Comment by yordanovagabriela** [comment]
Thanks. The issue is fixed now. :)
